services:
  - type: web
    name: falaahun-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    workingDirectory: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        scope: run_and_build
      - key: JWT_SECRET
        scope: run_and_build
